export const languages = {
    en: {
      title: 'Fake News Detector',
      textTab: 'Text',
      fileTab: 'File',
      urlTab: 'URL',
      textPlaceholder: 'Enter or paste your text here...',
      urlPlaceholder: 'Enter article URL',
      dropFile: 'Drag and drop your text file here',
      or: 'or',
      browse: 'Browse files',
      check: 'Check for News',
      result: 'Result',
      startListening: 'Start Voice Input',
      stopListening: 'Stop Listening',
      transcription: 'Transcription',
      nativeName: 'English',
    },
    hi: {
      title: 'फर्जी समाचार डिटेक्टर',
      textTab: 'टेक्स्ट',
      fileTab: 'फ़ाइल',
      urlTab: 'यूआरएल',
      textPlaceholder: 'यहां अपना टेक्स्ट दर्ज करें या पेस्ट करें...',
      urlPlaceholder: 'लेख का यूआरएल दर्ज करें',
      dropFile: 'अपनी टेक्स्ट फ़ाइल यहां खींचें और छोड़ें',
      or: 'या',
      browse: 'फ़ाइलें ब्राउज़ करें',
      check: 'समाचार की जांच करें',
      result: 'परिणाम',
      startListening: 'वॉइस इनपुट शुरू करें',
      stopListening: 'सुनना बंद करें',
      transcription: 'प्रतिलेखन',
      nativeName: 'हिंदी',
    },
    bn: {
      title: 'ভুয়া খবর সনাক্তকারী',
      textTab: 'টেক্সট',
      fileTab: 'ফাইল',
      urlTab: 'ইউআরএল',
      textPlaceholder: 'এখানে আপনার টেক্সট লিখুন বা পেস্ট করুন...',
      urlPlaceholder: 'নিবন্ধের ইউআরএল লিখুন',
      dropFile: 'আপনার টেক্সট ফাইল এখানে টেনে আনুন',
      or: 'অথবা',
      browse: 'ফাইল ব্রাউজ করুন',
      check: 'খবর যাচাই করুন',
      result: 'ফলাফল',
      startListening: 'ভয়েস ইনপুট শুরু করুন',
      stopListening: 'শোনা বন্ধ করুন',
      transcription: 'প্রতিলিপি',
      nativeName: 'বাংলা',
    },
    te: {
      title: 'నకిలీ వార్తల డిటెక్టర్',
      textTab: 'టెక్స్ట్',
      fileTab: 'ఫైల్',
      urlTab: 'URL',
      textPlaceholder: 'మీ టెక్స్ట్‌ని ఇక్కడ నమోదు చేయండి లేదా పేస్ట్ చేయండి...',
      urlPlaceholder: 'వార్తా URL ని నమోదు చేయండి',
      dropFile: 'మీ టెక్స్ట్ ఫైల్‌ని ఇక్కడ డ్రాగ్ చేసి డ్రాప్ చేయండి',
      or: 'లేదా',
      browse: 'ఫైల్‌లను బ్రౌజ్ చేయండి',
      check: 'వార్తలను తనిఖీ చేయండి',
      result: 'ఫలితం',
      startListening: 'వాయిస్ ఇన్‌పుట్ ప్రారంభించండి',
      stopListening: 'వినడం ఆపండి',
      transcription: 'ట్రాన్స్‌క్రిప్షన్',
      nativeName: 'తెలుగు',
    },
    mr: {
      title: 'बनावट बातम्या डिटेक्टर',
      textTab: 'मजकूर',
      fileTab: 'फाईल',
      urlTab: 'URL',
      textPlaceholder: 'तुमचा मजकूर येथे टाइप करा किंवा पेस्ट करा...',
      urlPlaceholder: 'लेखाची URL टाका',
      dropFile: 'तुमची मजकूर फाईल येथे ड्रॅग करा आणि ड्रॉप करा',
      or: 'किंवा',
      browse: 'फाईल्स ब्राउझ करा',
      check: 'बातम्या तपासा',
      result: 'निकाल',
      startListening: 'व्हॉइस इनपुट सुरू करा',
      stopListening: 'ऐकणे थांबवा',
      transcription: 'ट्रान्स्क्रिप्शन',
      nativeName: 'मराठी',
    },
    ta: {
      title: 'போலி செய்தி கண்டறிதல்',
      textTab: 'உரை',
      fileTab: 'கோப்பு',
      urlTab: 'URL',
      textPlaceholder: 'உங்கள் உரையை இங்கே உள்ளிடவும் அல்லது ஒட்டவும்...',
      urlPlaceholder: 'கட்டுரை URL ஐ உள்ளிடவும்',
      dropFile: 'உங்கள் உரை கோப்பை இங்கே இழுத்து விடவும்',
      or: 'அல்லது',
      browse: 'கோப்புகளை உலாவ',
      check: 'செய்திகளை சரிபார்க்கவும்',
      result: 'முடிவு',
      startListening: 'குரல் உள்ளீடு தொடங்கவும்',
      stopListening: 'கேட்பதை நிறுத்து',
      transcription: 'எழுத்துப்பெயர்ப்பு',
      nativeName: 'தமிழ்',
    },
    gu: {
      title: 'નકલી સમાચાર ડિટેક્ટર',
      textTab: 'ટેક્સ્ટ',
      fileTab: 'ફાઇલ',
      urlTab: 'URL',
      textPlaceholder: 'તમારો ટેક્સ્ટ અહીં દાખલ કરો અથવા પેસ્ટ કરો...',
      urlPlaceholder: 'લેખનું URL દાખલ કરો',
      dropFile: 'તમારી ટેક્સ્ટ ફાઇલ અહીં ખેંચો અને છોડો',
      or: 'અથવા',
      browse: 'ફાઇલ્સ બ્રાઉઝ કરો',
      check: 'સમાચાર તપાસો',
      result: 'પરિણામ',
      startListening: 'વૉઇસ ઇનપુટ શરૂ કરો',
      stopListening: 'સાંભળવાનું બંધ કરો',
      transcription: 'ટ્રાન્સક્રિપ્શન',
      nativeName: 'ગુજરાતી',
    },
    kn: {
      title: 'ನಕಲಿ ಸುದ್ದಿ ಪತ್ತೆಹಚ್ಚುವ',
      textTab: 'ಪಠ್ಯ',
      fileTab: 'ಫೈಲ್',
      urlTab: 'URL',
      textPlaceholder: 'ನಿಮ್ಮ ಪಠ್ಯವನ್ನು ಇಲ್ಲಿ ನಮೂದಿಸಿ ಅಥವಾ ಅಂಟಿಸಿ...',
      urlPlaceholder: 'ಲೇಖನದ URL ಅನ್ನು ನಮೂದಿಸಿ',
      dropFile: 'ನಿಮ್ಮ ಪಠ್ಯ ಫೈಲ್ ಅನ್ನು ಇಲ್ಲಿ ಎಳೆದು ಬಿಡಿ',
      or: 'ಅಥವಾ',
      browse: 'ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
      check: 'ಸುದ್ದಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
      result: 'ಫಲಿತಾಂಶ',
      startListening: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಪ್ರಾರಂಭಿಸಿ',
      stopListening: 'ಆಲಿಸುವುದನ್ನು ನಿಲ್ಲಿಸಿ',
      transcription: 'ಟ್ರಾನ್ಸ್‌ಕ್ರಿಪ್ಷನ್',
      nativeName: 'ಕನ್ನಡ',
    },
    ml: {
      title: 'വ്യാജ വാർത്ത കണ്ടെത്തൽ',
      textTab: 'ടെക്സ്റ്റ്',
      fileTab: 'ഫയൽ',
      urlTab: 'URL',
      textPlaceholder: 'നിങ്ങളുടെ ടെക്സ്റ്റ് ഇവിടെ നൽകുക അല്ലെങ്കിൽ പേസ്റ്റ് ചെയ്യുക...',
      urlPlaceholder: 'ലേഖനത്തിന്റെ URL നൽകുക',
      dropFile: 'നിങ്ങളുടെ ടെക്സ്റ്റ് ഫയൽ ഇവിടെ വലിച്ചിടുക',
      or: 'അല്ലെങ്കിൽ',
      browse: 'ഫയലുകൾ ബ്രൗസ് ചെയ്യുക',
      check: 'വാർത്തകൾ പരിശോധിക്കുക',
      result: 'ഫലം',
      startListening: 'വോയ്‌സ് ഇൻപുട്ട് ആരംഭിക്കുക',
      stopListening: 'കേൾക്കുന്നത് നിർത്തുക',
      transcription: 'ട്രാൻസ്ക്രിപ്ഷൻ',
      nativeName: 'മലയാളം',
    },
    pa: {
      title: 'ਨਕਲੀ ਖ਼ਬਰਾਂ ਦਾ ਪਤਾ ਲਗਾਉਣ ਵਾਲਾ',
      textTab: 'ਟੈਕਸਟ',
      fileTab: 'ਫਾਈਲ',
      urlTab: 'URL',
      textPlaceholder: 'ਆਪਣਾ ਟੈਕਸਟ ਇੱਥੇ ਦਰਜ ਕਰੋ ਜਾਂ ਪੇਸਟ ਕਰੋ...',
      urlPlaceholder: 'ਲੇਖ ਦਾ URL ਦਰਜ ਕਰੋ',
      dropFile: 'ਆਪਣੀ ਟੈਕਸਟ ਫਾਈਲ ਇੱਥੇ ਖਿੱਚੋ ਅਤੇ ਛੱਡੋ',
      or: 'ਜਾਂ',
      browse: 'ਫਾਈਲਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ',
      check: 'ਖ਼ਬਰਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
      result: 'ਨਤੀਜਾ',
      startListening: 'ਵੌਇਸ ਇਨਪੁੱਟ ਸ਼ੁਰੂ ਕਰੋ',
      stopListening: 'ਸੁਣਨਾ ਬੰਦ ਕਰੋ',
      transcription: 'ਟ੍ਰਾਂਸਕ੍ਰਿਪਸ਼ਨ',
      nativeName: 'ਪੰਜਾਬੀ',
    },
    ur: {
      title: 'جعلی خبروں کا ڈیٹیکٹر',
      textTab: 'متن',
      fileTab: 'فائل',
      urlTab: 'یو آر ایل',
      textPlaceholder: 'اپنا متن یہاں درج کریں یا پیسٹ کریں...',
      urlPlaceholder: 'مضمون کا یو آر ایل درج کریں',
      dropFile: 'اپنی متنی فائل یہاں کھینچیں اور چھوڑیں',
      or: 'یا',
      browse: 'فائلیں براؤز کریں',
      check: 'خبروں کی جانچ کریں',
      result: 'نتیجہ',
      startListening: 'صوتی ان پٹ شروع کریں',
      stopListening: 'سننا بند کریں',
      transcription: 'ٹرانسکرپشن',
      nativeName: 'اردو',
    },
    or: {
      title: 'ନକଲି ଖବର ଡିଟେକ୍ଟର',
      textTab: 'ଟେକ୍ସଟ',
      fileTab: 'ଫାଇଲ',
      urlTab: 'URL',
      textPlaceholder: 'ଆପଣଙ୍କର ଟେକ୍ସଟ ଏଠାରେ ଲେଖନ୍ତୁ କିମ୍ବା ପେଷ୍ଟ କରନ୍ତୁ...',
      urlPlaceholder: 'ଆର୍ଟିକଲ URL ପ୍ରବେଶ କରନ୍ତୁ',
      dropFile: 'ଆପଣଙ୍କର ଟେକ୍ସଟ ଫାଇଲ ଏଠାରେ ଟାଣି ଆଣନ୍ତୁ',
      or: 'କିମ୍ବା',
      browse: 'ଫାଇଲ ବ୍ରାଉଜ କରନ୍ତୁ',
      check: 'ଖବର ଯାଞ୍ଚ କରନ୍ତୁ',
      result: 'ଫଳାଫଳ',
      startListening: 'ଭଏସ ଇନପୁଟ ଆରମ୍ଭ କରନ୍ତୁ',
      stopListening: 'ଶୁଣିବା ବନ୍ଦ କରନ୍ତୁ',
      transcription: 'ଟ୍ରାନ୍ସକ୍ରିପସନ',
      nativeName: 'ଓଡ଼ିଆ',
    },
    as: {
      title: 'ভুৱা বাতৰি ডিটেক্টৰ',
      textTab: 'পাঠ',
      fileTab: 'ফাইল',
      urlTab: 'URL',
      textPlaceholder: 'আপোনাৰ পাঠ ইয়াত লিখক বা পেষ্ট কৰক...',
      urlPlaceholder: 'প্ৰবন্ধৰ URL প্ৰৱেশ কৰক',
      dropFile: 'আপোনাৰ পাঠ ফাইল ইয়াত টানি আনক',
      or: 'বা',
      browse: 'ফাইল ব্ৰাউজ কৰক',
      check: 'বাতৰি পৰীক্ষা কৰক',
      result: 'ফলাফল',
      startListening: 'কণ্ঠ ইনপুট আৰম্ভ কৰক',
      stopListening: 'শুনা বন্ধ কৰক',
      transcription: 'ট্ৰান্সক্ৰিপচন',
      nativeName: 'অসমীয়া',
    },
    mai: {
      title: 'फर्जी समाचार डिटेक्टर',
      textTab: 'टेक्स्ट',
      fileTab: 'फाइल',
      urlTab: 'URL',
      textPlaceholder: 'अपन टेक्स्ट एतय टाइप करू वा पेस्ट करू...',
      urlPlaceholder: 'लेख केर URL दर्ज करू',
      dropFile: 'अपन टेक्स्ट फाइल एतय खींचू आ छोड़ू',
      or: 'वा',
      browse: 'फाइल ब्राउज करू',
      check: 'समाचार जांचू',
      result: 'परिणाम',
      startListening: 'आवाज इनपुट शुरू करू',
      stopListening: 'सुनब बंद करू',
      transcription: 'ट्रांसक्रिप्शन',
      nativeName: 'मैथिली',
    },
    sa: {
      title: 'मिथ्यावार्ता अन्वेषकः',
      textTab: 'पाठः',
      fileTab: 'सञ्चिका',
      urlTab: 'URL',
      textPlaceholder: 'अत्र पाठं लिखतु अथवा योजयतु...',
      urlPlaceholder: 'लेखस्य URL प्रविष्टं करोतु',
      dropFile: 'अत्र पाठसञ्चिकां कर्षयतु',
      or: 'अथवा',
      browse: 'सञ्चिकाः अन्वेषयतु',
      check: 'वार्तां परीक्षयतु',
      result: 'परिणामः',
      startListening: 'ध्वनिः आरभ्यताम्',
      stopListening: 'श्रवणं विरम्यताम्',
      transcription: 'लिप्यन्तरणम्',
      nativeName: 'संस्कृतम्',
    },
    kok: {
      title: 'फट बातमी सोदपी',
      textTab: 'मजकूर',
      fileTab: 'फायल',
      urlTab: 'URL',
      textPlaceholder: 'तुमचो मजकूर हांगा बरयात वा पेस्ट करात...',
      urlPlaceholder: 'लेखाचो URL दवरात',
      dropFile: 'तुमची मजकूर फायल हांगा ओडून सोडात',
      or: 'वा',
      browse: 'फायली ब्राउज करात',
      check: 'बातमी तपासात',
      result: 'फलीत',
      startListening: 'आवाज इनपुट सुरू करात',
      stopListening: 'आयकप बंद करात',
      transcription: 'ट्रान्स्क्रिप्शन',
      nativeName: 'कोंकणी',
    },
  };